#!/usr/bin/env bash
LOG_FILE="__LOG_FILE__"
EXIT_CODE="__EXIT_CODE__"

echo "$@" >> "$LOG_FILE"

if [ "$#" -lt 2 ]; then
  exit "$EXIT_CODE"
fi

POSITIONS=()
while [ "$#" -gt 0 ]; do
  CURRENT="$1"
  shift
  if [ "${CURRENT#-}" != "$CURRENT" ]; then
    continue
  fi
  POSITIONS+=("$CURRENT")
done

LAST="${POSITIONS[${#POSITIONS[@]}-1]}"
FIRST_INPUT=""
for PATH_ARG in "${POSITIONS[@]}"; do
  if [ -f "$PATH_ARG" ]; then
    FIRST_INPUT="$PATH_ARG"
    break
  fi
done

if [ -n "$LAST" ]; then
  OUT_EXT="${LAST##*.}"
  OUT_EXT="${OUT_EXT,,}"
  if [ "$OUT_EXT" = "jpg" ] || [ "$OUT_EXT" = "jpeg" ]; then
    cat <<'JPEG' | base64 -d > "$LAST"
/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgo/wAARCAABAAEDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9/KKKKAP/2Q==
JPEG
  elif [ "$OUT_EXT" = "tif" ] || [ "$OUT_EXT" = "tiff" ]; then
    cat <<'TIFF' | base64 -d > "$LAST"
SUkqAAgAAAAKAAABBAABAAAAAQAAAAEBBAABAAAAAQAAAAIBAwADAAAAhgAAAAMBAwABAAAAAQAAAAYBAwABAAAAAgAAABEBBAABAAAAjAAAABUBAwABAAAAAwAAABYBBAABAAAAAQAAABcBBAABAAAAAwAAABwBAwABAAAAAQAAAAAAAAAIAAgACAD///8=
TIFF
  elif [ -n "$FIRST_INPUT" ] && [ "$FIRST_INPUT" != "$LAST" ]; then
    cp "$FIRST_INPUT" "$LAST"
  else
    touch "$LAST"
  fi
fi

exit "$EXIT_CODE"
