//! `SeaORM` Entity, @generated by sea-orm-codegen

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "image_tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub image_id: i64,
    pub tag_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub position: i64,
    #[sea_orm(
        belongs_to,
        from = "image_id",
        to = "image_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub images: BelongsTo<super::images::Entity>,
    #[sea_orm(
        belongs_to,
        from = "tag_id",
        to = "tag_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub tags: BelongsTo<super::tags::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
