//! `SeaORM` Entity, @generated by sea-orm-codegen

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "images")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub image_id: i64,
    pub position: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub raw_path: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub sooc_sidecar_path: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub relative_path: String,
    #[sea_orm(column_type = "Text")]
    pub file_name: String,
    pub exif_capture_timestamp: Option<i64>,
    pub exif_rating: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub exif_focal_length: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub exif_aperture: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub exif_shutter_speed: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub exif_iso: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub exif_camera_model: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub exif_lens_model: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub exif_shooting_mode: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub exif_exposure_compensation: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub exif_flash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub exif_note: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub preview_status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub preview_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub preview_error: Option<String>,
    pub preview_duration_ms: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub preview_render_key: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub preview_updated_at: String,
    pub selected_profile_index: i64,
    pub rating: i64,
    #[sea_orm(column_type = "Text")]
    pub label: String,
    #[sea_orm(column_type = "Text")]
    pub notes: String,
    #[sea_orm(column_type = "Text")]
    pub rating_source: String,
    #[sea_orm(column_type = "Text")]
    pub tags_source: String,
    #[sea_orm(column_type = "Text")]
    pub notes_source: String,
    #[sea_orm(column_type = "Text")]
    pub codex_status: String,
    pub codex_flags_tags: i64,
    pub codex_flags_note: i64,
    pub codex_flags_rating: i64,
    #[sea_orm(column_type = "Text")]
    pub codex_model: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub codex_analysis_key: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub codex_error: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub codex_updated_at: String,
    #[sea_orm(column_type = "Double")]
    pub retouch_exposure: f64,
    #[sea_orm(column_type = "Double")]
    pub retouch_highlights: f64,
    #[sea_orm(column_type = "Double")]
    pub retouch_shadows: f64,
    #[sea_orm(column_type = "Double")]
    pub retouch_whites: f64,
    #[sea_orm(column_type = "Double")]
    pub retouch_blacks: f64,
    #[sea_orm(column_type = "Double")]
    pub retouch_temperature: f64,
    #[sea_orm(column_type = "Double")]
    pub retouch_offset: f64,
    #[sea_orm(column_type = "Double")]
    pub retouch_clarity: f64,
    #[sea_orm(column_type = "Double", nullable)]
    pub retouch_crop_x: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub retouch_crop_y: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub retouch_crop_width: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub retouch_crop_height: Option<f64>,
    #[sea_orm(column_type = "Double")]
    pub retouch_rotation_degrees: f64,
    pub publish_profiles_default: i64,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub exif_active_d_lighting: Option<String>,
    pub source_file_size_bytes: Option<i64>,
    pub source_width: Option<i64>,
    pub source_height: Option<i64>,
    pub exif_focus_frame_width: Option<i64>,
    pub exif_focus_frame_height: Option<i64>,
    pub exif_auto_iso: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub exif_iso_auto_hi_limit: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub exif_white_balance_mode: Option<String>,
    pub exif_white_balance_temperature: Option<i64>,
    pub exif_white_balance_offset: Option<i64>,
    pub exif_shutter_count: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub exif_shutter_mode: Option<String>,
    pub exif_silent_photography: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub exif_release_mode: Option<String>,
    #[sea_orm(has_many)]
    pub image_exif_tags: HasMany<super::image_exif_tags::Entity>,
    #[sea_orm(has_many)]
    pub image_focus_regions: HasMany<super::image_focus_regions::Entity>,
    #[sea_orm(has_many)]
    pub image_labels: HasMany<super::image_labels::Entity>,
    #[sea_orm(has_many)]
    pub image_profile_bw_filters: HasMany<super::image_profile_bw_filters::Entity>,
    #[sea_orm(has_many)]
    pub image_profile_renders: HasMany<super::image_profile_renders::Entity>,
    #[sea_orm(has_many)]
    pub image_publish_profiles: HasMany<super::image_publish_profiles::Entity>,
    #[sea_orm(has_many)]
    pub review_settings: HasMany<super::review_settings::Entity>,
    #[sea_orm(has_many, via = "image_tags")]
    pub tags: HasMany<super::tags::Entity>,
    #[sea_orm(has_many)]
    pub panorama_project_images: HasMany<super::panorama_project_images::Entity>,
    #[sea_orm(has_many)]
    pub panorama_results: HasMany<super::panorama_projects::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
