//! `SeaORM` Entity, @generated by sea-orm-codegen

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "image_profile_renders")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub image_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub position: i64,
    pub profile_index: i64,
    #[sea_orm(column_type = "Text")]
    pub profile_stem: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub display_name: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub output_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error: Option<String>,
    pub duration_ms: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub render_key: Option<String>,
    pub width: Option<i64>,
    pub height: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub processing_key: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "image_id",
        to = "image_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub images: BelongsTo<super::images::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
