//! `SeaORM` Entity, @generated by sea-orm-codegen

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "profile_sharpening")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub profile_index: i64,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub scope: String,
    pub present: i64,
    #[sea_orm(column_type = "Double")]
    pub amount: f64,
    #[sea_orm(column_type = "Double")]
    pub radius: f64,
    #[sea_orm(column_type = "Double")]
    pub detail: f64,
    #[sea_orm(column_type = "Double")]
    pub masking: f64,
    #[sea_orm(
        belongs_to,
        from = "profile_index",
        to = "profile_index",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub profiles: BelongsTo<super::profiles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
