//! `SeaORM` Entity, @generated by sea-orm-codegen

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "profile_adjustments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub profile_index: i64,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub scope: String,
    #[sea_orm(column_type = "Double")]
    pub exposure: f64,
    #[sea_orm(column_type = "Double")]
    pub contrast: f64,
    #[sea_orm(column_type = "Double")]
    pub highlights: f64,
    #[sea_orm(column_type = "Double")]
    pub shadows: f64,
    #[sea_orm(column_type = "Double")]
    pub whites: f64,
    #[sea_orm(column_type = "Double")]
    pub blacks: f64,
    #[sea_orm(column_type = "Double")]
    pub saturation: f64,
    #[sea_orm(column_type = "Double")]
    pub vibrance: f64,
    #[sea_orm(column_type = "Double")]
    pub clarity: f64,
    #[sea_orm(column_type = "Double")]
    pub parametric_shadows: f64,
    #[sea_orm(column_type = "Double")]
    pub parametric_darks: f64,
    #[sea_orm(column_type = "Double")]
    pub parametric_lights: f64,
    #[sea_orm(column_type = "Double")]
    pub parametric_highlights: f64,
    #[sea_orm(column_type = "Double")]
    pub parametric_shadow_split: f64,
    #[sea_orm(column_type = "Double")]
    pub parametric_midtone_split: f64,
    #[sea_orm(column_type = "Double")]
    pub parametric_highlight_split: f64,
    #[sea_orm(column_type = "Double")]
    pub calibration_red_hue: f64,
    #[sea_orm(column_type = "Double")]
    pub calibration_red_saturation: f64,
    #[sea_orm(column_type = "Double")]
    pub calibration_green_hue: f64,
    #[sea_orm(column_type = "Double")]
    pub calibration_green_saturation: f64,
    #[sea_orm(column_type = "Double")]
    pub calibration_blue_hue: f64,
    #[sea_orm(column_type = "Double")]
    pub calibration_blue_saturation: f64,
    #[sea_orm(
        belongs_to,
        from = "profile_index",
        to = "profile_index",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub profiles: BelongsTo<super::profiles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
