//! `SeaORM` Entity, @generated by sea-orm-codegen

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "profile_pp3_sections")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub profile_index: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub section_position: i64,
    #[sea_orm(column_type = "Text")]
    pub source: String,
    #[sea_orm(column_type = "Text")]
    pub section: String,
    #[sea_orm(has_many)]
    pub profile_pp3_entries: HasMany<super::profile_pp3_entries::Entity>,
    #[sea_orm(
        belongs_to,
        from = "profile_index",
        to = "profile_index",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub profiles: BelongsTo<super::profiles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
