//! `SeaORM` Entity, @generated by sea-orm-codegen

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "profiles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub profile_index: i64,
    pub position: i64,
    #[sea_orm(column_type = "Text")]
    pub identity: String,
    #[sea_orm(column_type = "Text")]
    pub selector: String,
    #[sea_orm(column_type = "Text")]
    pub stem: String,
    pub sampler_added: i64,
    pub enabled_by_default: i64,
    #[sea_orm(column_type = "Double")]
    pub retouch_exposure: f64,
    #[sea_orm(column_type = "Double")]
    pub retouch_highlights: f64,
    #[sea_orm(column_type = "Double")]
    pub retouch_shadows: f64,
    #[sea_orm(column_type = "Double")]
    pub retouch_whites: f64,
    #[sea_orm(column_type = "Double")]
    pub retouch_blacks: f64,
    #[sea_orm(column_type = "Double")]
    pub retouch_temperature: f64,
    #[sea_orm(column_type = "Double")]
    pub retouch_offset: f64,
    #[sea_orm(column_type = "Double")]
    pub retouch_clarity: f64,
    pub metadata_present: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub profile_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub profile_uuid: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub look_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub look_uuid: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_profile_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_profile_uuid: Option<String>,
    pub has_camera_raw_settings: i64,
    pub grain_amount: Option<i64>,
    pub grain_size: Option<i64>,
    pub grain_frequency: Option<i64>,
    pub has_hald: i64,
    pub has_pp3: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub pp3_name: Option<String>,
    #[sea_orm(has_many)]
    pub profile_adjustments: HasMany<super::profile_adjustments::Entity>,
    #[sea_orm(has_many)]
    pub profile_hsl_values: HasMany<super::profile_hsl_values::Entity>,
    #[sea_orm(has_many)]
    pub profile_sharpenings: HasMany<super::profile_sharpening::Entity>,
    #[sea_orm(has_many)]
    pub profile_tone_curve_points: HasMany<super::profile_tone_curve_points::Entity>,
    #[sea_orm(has_many)]
    pub profile_pp3_sections: HasMany<super::profile_pp3_sections::Entity>,
    #[sea_orm(has_many, via = "profile_pp3_sections")]
    pub profile_pp3_entries: HasMany<super::profile_pp3_entries::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
