//! `SeaORM` Entity, @generated by sea-orm-codegen

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "review_settings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub next_id: i64,
    pub current_image_id: Option<i64>,
    pub min_rating: i64,
    pub exif_schema_version: i64,
    #[sea_orm(column_type = "Text")]
    pub input_root: String,
    #[sea_orm(column_type = "Text")]
    pub output_root: String,
    #[sea_orm(
        belongs_to,
        from = "current_image_id",
        to = "image_id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub images: BelongsTo<Option<super::images::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
