//! `SeaORM` Entity, @generated by sea-orm-codegen

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub tag_id: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub tag: String,
    #[sea_orm(has_many, via = "image_tags")]
    pub images: HasMany<super::images::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
