// Typed Rust API fixtures keep browser regressions independent of cameras,
// external renderers, and network services while exercising realistic state.
import type { ReviewStateData, SamplerJob, DiffusionJob } from "../review/core/types";

const updated = "2026-09-05T10:00:00Z";
const adjustments = {
  exposure: 0,
  contrast: 0,
  highlights: 0,
  shadows: 0,
  whites: 0,
  blacks: 0,
  temperature: 0,
  offset: 0,
  clarity: 0,
};
export const diffusion = {
  method: "multi-scale-mist" as const,
  softness: 0,
  highlight_glow: 0,
  softness_radius_percent: 100,
  glow_radius_percent: 100,
  intensity_percent: 100,
  highlight_reach: 50,
};

/** Return a fresh review session so parallel browser tests cannot share edits. */
export function reviewFixture(): ReviewStateData {
  return {
    version: "22.15.1",
    invocation: "mini-film daemon inbox output --profile Classic",
    client_count: 1,
    codex: { enabled: false, flags: null, model: null, queued: 0, processing: 0, done: 0, failed: 0 },
    diffusion_default: diffusion,
    profile_diffusion_settings: [],
    publish_jobs: [],
    capabilities: { panorama: { available: true, reason: null }, sampler: true, diffusion: true },
    panorama: { busy: false, projects: [] },
    bursts: [],
    publish_root: "/pictures/published",
    ui: { current_image_id: 1, min_rating: 0, labels: [] },
    publish_defaults: {
      album: "Review fixture",
      output_format: "jpg",
      jpg_quality: 92,
      resize: null,
      long_edge: null,
      max_width: null,
      max_height: null,
      jpeg_subsampling: "s444",
      strip_metadata: false,
      progressive_jpeg: false,
      gallery: "modern",
      gallery_thumbnail_long_edge: 600,
      gallery_columns: 3,
      grain_engine: "rfgrfast",
      normalize_grain_mpix: 24,
    },
    profiles: ["Classic", "Soft"].map((name, index) => ({
      index,
      identity: name,
      selector: name,
      stem: name,
      sampler_added: false,
      enabled_by_default: true,
      configured_from_cli: true,
      retouch_base: structuredClone(adjustments),
      metadata: null,
    })),
    images: [1, 2, 3].map((id) => ({
      id,
      source_type: "raw",
      processing_mode: "profiled",
      relative_path: `frame-${id}.NEF`,
      file_name: `frame-${id}.NEF`,
      source_file_size_bytes: 24_000_000,
      source_width: 1200,
      source_height: 800,
      exif: {
        capture_timestamp: 1_788_602_400,
        capture_subsecond: null,
        rating: 2,
        file_size_bytes: 24_000_000,
        image_width: 1200,
        image_height: 800,
        focus_frame_width: 1200,
        focus_frame_height: 800,
        focus_regions: [{ x: 0.45, y: 0.35, width: 0.1, height: 0.15, primary: true }],
        focal_length: "50 mm",
        aperture: "f/2.8",
        shutter_speed: "1/250",
        iso: "100",
        auto_iso: false,
        iso_auto_hi_limit: null,
        white_balance_mode: "Daylight",
        white_balance_temperature: 5500,
        white_balance_offset: 0,
        camera_model: "Nikon Z 7_2",
        shutter_count: 1000,
        shutter_mode: null,
        silent_photography: null,
        release_mode: null,
        lens_model: "50mm f/1.8",
        shooting_mode: "Aperture Priority",
        exposure_compensation: "0",
        flash: null,
        active_d_lighting: null,
        tags: [],
        note: null,
      },
      preview_status: "done",
      thumbnail_url: `fixture/${id}.svg`,
      preview_url: `fixture/${id}.svg`,
      crop_source_url: `fixture/${id}.svg`,
      crop_source_updated_at: updated,
      full_url: `fixture/${id}.svg`,
      preview_error: null,
      preview_duration_ms: 80,
      preview_retouch_pending: false,
      preview_updated_at: updated,
      selected_profile_index: 0,
      rating: 2,
      label: "none",
      labels: [],
      tags: ["12"],
      notes: "Camera note",
      rating_source: "camera",
      tags_source: "manual",
      notes_source: "camera",
      codex: {
        status: "skipped",
        flags: { tags: false, note: false, rating: false },
        model: "",
        error: null,
        updated_at: updated,
      },
      retouch: { adjustments: structuredClone(adjustments), crop: null, rotation_degrees: 0 },
      publish_profile_indexes: [0, 1],
      profile_bw_filters: [],
      profile_diffusion_settings: [],
      profiles: ["Classic", "Soft"].map((name, index) => ({
        profile_index: index,
        profile_stem: name,
        display_name: name,
        enabled: true,
        status: "done",
        url: `fixture/${id}-${index}.svg`,
        base_url: `fixture/${id}-${index}-base.svg`,
        error: null,
        duration_ms: 100,
        file_size_bytes: 160_000,
        width: 1200,
        height: 800,
        retouch_pending: false,
        dcp_profile_filename: null,
        lcp_profile_filename: null,
        bw_filter_eligible: false,
        bw_filter: "none",
        diffusion: { settings: diffusion, source: "daemon" },
        diffusion_settings: diffusion,
        diffusion_source: "daemon",
        updated_at: updated,
      })),
      updated_at: updated,
    })),
  };
}

/** Provide a finished sampler result that also supports simulated polling states. */
export function samplerFixture(): SamplerJob {
  return {
    id: 7,
    image_id: 1,
    file_name: "frame-1.NEF",
    status: "done",
    source_url: "fixture/1.svg",
    source_width: 1200,
    source_height: 800,
    completed: 1,
    total: 1,
    failed: 0,
    workers: 1,
    error: null,
    entries: [
      {
        key: "classic",
        name: "Classic",
        filename: "Classic.xmp",
        parts: ["Film", "Classic"],
        status: "done",
        thumbnail_url: "fixture/1.svg",
        duration_ms: 100,
        error: null,
        current_enabled: true,
        all_enabled: false,
        configured_from_cli: true,
        selected: true,
      },
    ],
  };
}

/** Provide a finished diffusion preview without needing RawTherapee. */
export function diffusionFixture(): DiffusionJob {
  return {
    id: 9,
    image_id: 1,
    profile_index: 0,
    status: "done",
    settings: diffusion,
    before_url: "fixture/1.svg",
    after_url: "fixture/1.svg",
    preview_width: 1200,
    preview_height: 800,
    focus_source: "camera-focus",
    detail_areas: [],
    error: null,
  };
}
