use std::path::PathBuf;

use clap::{Parser, Subcommand, ValueEnum};

#[derive(Parser, Debug)]
#[command(
    version,
    about = "Develop RAW files with Lightroom-style film profile Hald CLUTs"
)]
pub(crate) struct Cli {
    #[command(subcommand)]
    pub(crate) command: CommandKind,
}

#[derive(Subcommand, Debug)]
pub(crate) enum CommandKind {
    /// Convert Adobe Camera Raw crs:RGBTable XMP profiles to Hald CLUT PNGs.
    Hald {
        /// XMP profile file or directory to convert.
        input: PathBuf,

        /// Output PNG path for a single file, or output directory for a directory input.
        #[arg(short, long, default_value = "hald")]
        output: PathBuf,

        /// Hald level. Level 8 produces a 64x64x64 CLUT stored as a 512x512 PNG.
        #[arg(short = 'l', long, default_value_t = 8)]
        hald_level: u32,

        /// Overwrite existing output files.
        #[arg(long)]
        overwrite: bool,

        /// Print table metadata without writing PNGs.
        #[arg(long)]
        info_only: bool,
    },

    /// Run dcraw, then apply a Hald CLUT with GraphicsMagick/ImageMagick convert.
    Apply {
        /// RAW file to develop.
        raw: PathBuf,

        /// Output image path.
        #[arg(short, long)]
        output: PathBuf,

        /// Profile selector: Hald PNG path, RGBTable XMP path, or profile name.
        #[arg(short, long)]
        profile: String,

        /// Directory containing generated Hald PNGs, used when --profile is a name.
        #[arg(long, default_value = "hald")]
        hald_dir: PathBuf,

        /// Directory tree containing XMP profiles, used when --profile is a name.
        #[arg(long, default_value = ".")]
        profiles_root: PathBuf,

        /// Hald level to use when --profile points to an XMP or resolves to an XMP.
        #[arg(short = 'l', long, default_value_t = 8)]
        hald_level: u32,

        /// Extra arguments passed to dcraw before the RAW path.
        #[arg(long, value_delimiter = ' ', default_value = "-T -6 -W -w -o 1")]
        dcraw_args: Vec<String>,

        /// RAW decoder: auto tries RawTherapee first and falls back to dcraw.
        #[arg(long, value_enum, default_value_t = RawEngine::Auto)]
        raw_engine: RawEngine,

        /// Path to rawtherapee-cli binary.
        #[arg(long, default_value = "rawtherapee-cli")]
        rawtherapee: PathBuf,

        /// Camera input ICC profile for dcraw, or "embed". If omitted, dcraw uses its camera matrix.
        #[arg(long)]
        camera_profile: Option<String>,

        /// Path to dcraw binary.
        #[arg(long, default_value = "dcraw")]
        dcraw: PathBuf,

        /// Path to convert binary.
        #[arg(long, default_value = "convert")]
        convert: PathBuf,

        /// Keep the intermediate TIFF generated by dcraw.
        #[arg(long)]
        keep_intermediate: Option<PathBuf>,

        /// Disable Lightroom XMP grain emulation.
        #[arg(long)]
        no_grain: bool,

        /// Override grain as amount,size,frequency, each 0..100. Example: --grain 30,45,45
        #[arg(long)]
        grain: Option<String>,

        /// Built-in grain override: light, medium, or heavy.
        #[arg(long)]
        grain_preset: Option<String>,

        /// Seed for deterministic generated grain. Defaults to current time of day.
        #[arg(long)]
        grain_seed: Option<u64>,

        /// JPEG quality when output path ends in .jpg or .jpeg.
        #[arg(long, default_value_t = 95)]
        jpg_quality: u8,

        /// Resize final output with GraphicsMagick geometry, for example 3000x3000 or 3000x3000>.
        #[arg(long)]
        resize: Option<String>,

        /// Resize final output so the longest edge is at most this many pixels.
        #[arg(long)]
        long_edge: Option<u32>,

        /// Resize final output so width is at most this many pixels.
        #[arg(long)]
        max_width: Option<u32>,

        /// Resize final output so height is at most this many pixels.
        #[arg(long)]
        max_height: Option<u32>,

        /// JPEG chroma subsampling.
        #[arg(long, value_enum, default_value_t = JpegSubsampling::S444)]
        jpeg_subsampling: JpegSubsampling,

        /// Strip profiles and text metadata from final output.
        #[arg(long)]
        strip_metadata: bool,

        /// Write progressive/interlaced JPEG output.
        #[arg(long)]
        progressive_jpeg: bool,
    },

    /// Apply a profile to every DNG/NEF file in an input folder and write JPEGs.
    Batch {
        /// Input folder scanned recursively for .dng/.DNG/.nef/.NEF files.
        input: PathBuf,

        /// Output folder. It is created if it does not exist.
        output: PathBuf,

        /// Profile selector: Hald PNG path, RGBTable XMP path, preset XMP path, or profile name.
        #[arg(short, long)]
        profile: String,

        /// Directory containing generated Hald PNGs, used when --profile is a name.
        #[arg(long, default_value = "hald")]
        hald_dir: PathBuf,

        /// Directory tree containing XMP profiles, used when --profile is a name.
        #[arg(long, default_value = ".")]
        profiles_root: PathBuf,

        /// Hald level to use when --profile points to an XMP or resolves to an XMP.
        #[arg(short = 'l', long, default_value_t = 8)]
        hald_level: u32,

        /// Extra arguments passed to dcraw before the RAW path.
        #[arg(long, value_delimiter = ' ', default_value = "-T -6 -W -w -o 1")]
        dcraw_args: Vec<String>,

        /// RAW decoder: auto tries RawTherapee first and falls back to dcraw.
        #[arg(long, value_enum, default_value_t = RawEngine::Auto)]
        raw_engine: RawEngine,

        /// Path to rawtherapee-cli binary.
        #[arg(long, default_value = "rawtherapee-cli")]
        rawtherapee: PathBuf,

        /// Camera input ICC profile for dcraw, or "embed". If omitted, dcraw uses its camera matrix.
        #[arg(long)]
        camera_profile: Option<String>,

        /// Path to dcraw binary.
        #[arg(long, default_value = "dcraw")]
        dcraw: PathBuf,

        /// Path to convert binary.
        #[arg(long, default_value = "convert")]
        convert: PathBuf,

        /// Disable Lightroom XMP grain emulation.
        #[arg(long)]
        no_grain: bool,

        /// Override grain as amount,size,frequency, each 0..100. Example: --grain 30,45,45
        #[arg(long)]
        grain: Option<String>,

        /// Built-in grain override: light, medium, or heavy.
        #[arg(long)]
        grain_preset: Option<String>,

        /// Base seed for deterministic generated grain. Defaults to current time of day.
        #[arg(long)]
        grain_seed: Option<u64>,

        /// JPEG quality for every output file.
        #[arg(long, default_value_t = 95)]
        jpg_quality: u8,

        /// Resize final JPEGs with GraphicsMagick geometry, for example 3000x3000 or 3000x3000>.
        #[arg(long)]
        resize: Option<String>,

        /// Resize final JPEGs so the longest edge is at most this many pixels.
        #[arg(long)]
        long_edge: Option<u32>,

        /// Resize final JPEGs so width is at most this many pixels.
        #[arg(long)]
        max_width: Option<u32>,

        /// Resize final JPEGs so height is at most this many pixels.
        #[arg(long)]
        max_height: Option<u32>,

        /// JPEG chroma subsampling.
        #[arg(long, value_enum, default_value_t = JpegSubsampling::S444)]
        jpeg_subsampling: JpegSubsampling,

        /// Strip profiles and text metadata from final JPEGs.
        #[arg(long)]
        strip_metadata: bool,

        /// Write progressive/interlaced JPEGs.
        #[arg(long)]
        progressive_jpeg: bool,
    },

    /// Render every resolvable XMP profile as a labeled contact-sheet thumbnail.
    Sampler {
        /// RAW file to use as the sampler source.
        raw: PathBuf,

        /// Output contact sheet JPEG path.
        #[arg(short, long)]
        output: PathBuf,

        /// Directory tree containing XMP profiles and presets to sample.
        #[arg(long, default_value = ".")]
        profiles_root: PathBuf,

        /// Hald level to use for temporary XMP profile conversion.
        #[arg(short = 'l', long, default_value_t = 8)]
        hald_level: u32,

        /// Extra arguments passed to dcraw before the RAW path.
        #[arg(long, value_delimiter = ' ', default_value = "-T -6 -W -w -o 1")]
        dcraw_args: Vec<String>,

        /// RAW decoder: auto tries RawTherapee first and falls back to dcraw.
        #[arg(long, value_enum, default_value_t = RawEngine::Auto)]
        raw_engine: RawEngine,

        /// Path to rawtherapee-cli binary.
        #[arg(long, default_value = "rawtherapee-cli")]
        rawtherapee: PathBuf,

        /// Camera input ICC profile for dcraw, or "embed". If omitted, dcraw uses its camera matrix.
        #[arg(long)]
        camera_profile: Option<String>,

        /// Path to dcraw binary.
        #[arg(long, default_value = "dcraw")]
        dcraw: PathBuf,

        /// Path to convert binary.
        #[arg(long, default_value = "convert")]
        convert: PathBuf,

        /// Path to montage binary.
        #[arg(long, default_value = "montage")]
        montage: PathBuf,

        /// Disable Lightroom XMP grain emulation.
        #[arg(long)]
        no_grain: bool,

        /// Base seed for deterministic generated grain. Defaults to current time of day.
        #[arg(long)]
        grain_seed: Option<u64>,

        /// Thumbnail longest edge in pixels.
        #[arg(long, default_value_t = 512)]
        thumbnail_long_edge: u32,

        /// JPEG quality for thumbnails and the final contact sheet.
        #[arg(long, default_value_t = 95)]
        jpg_quality: u8,

        /// JPEG chroma subsampling for thumbnails and the final contact sheet.
        #[arg(long, value_enum, default_value_t = JpegSubsampling::S444)]
        jpeg_subsampling: JpegSubsampling,

        /// Strip profiles and text metadata from generated JPEGs.
        #[arg(long)]
        strip_metadata: bool,
    },
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, ValueEnum)]
pub(crate) enum RawEngine {
    Auto,
    Rawtherapee,
    Dcraw,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, ValueEnum)]
pub(crate) enum JpegSubsampling {
    S444,
    S422,
    S420,
}

impl JpegSubsampling {
    pub(crate) fn graphicsmagick_sampling_factor(self) -> &'static str {
        match self {
            JpegSubsampling::S444 => "1x1,1x1,1x1",
            JpegSubsampling::S422 => "2x1,1x1,1x1",
            JpegSubsampling::S420 => "2x2,1x1,1x1",
        }
    }
}

#[derive(Clone, Debug)]
pub(crate) struct ExportOptions {
    pub(crate) jpg_quality: u8,
    pub(crate) resize: Option<String>,
    pub(crate) long_edge: Option<u32>,
    pub(crate) max_width: Option<u32>,
    pub(crate) max_height: Option<u32>,
    pub(crate) jpeg_subsampling: JpegSubsampling,
    pub(crate) strip_metadata: bool,
    pub(crate) progressive_jpeg: bool,
}
