use std::{
    fs::{self, File},
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

use anyhow::{Context, Result, bail};
use clap::{Parser, Subcommand};
use mini_film::{
    GrainSettings, HaldOptions, apply_grain, convert_path, convert_xmp_to_hald,
    extract_film_recipe, profile_info_line, try_convert_dir,
};
use tempfile::Builder;
use walkdir::WalkDir;

#[derive(Parser, Debug)]
#[command(
    version,
    about = "Develop RAW files with Lightroom-style film profile Hald CLUTs"
)]
struct Cli {
    #[command(subcommand)]
    command: CommandKind,
}

#[derive(Subcommand, Debug)]
enum CommandKind {
    /// Convert Adobe Camera Raw crs:RGBTable XMP profiles to Hald CLUT PNGs.
    Hald {
        /// XMP profile file or directory to convert.
        input: PathBuf,

        /// Output PNG path for a single file, or output directory for a directory input.
        #[arg(short, long, default_value = "hald")]
        output: PathBuf,

        /// Hald level. Level 8 produces a 64x64x64 CLUT stored as a 512x512 PNG.
        #[arg(short = 'l', long, default_value_t = 8)]
        hald_level: u32,

        /// Overwrite existing output files.
        #[arg(long)]
        overwrite: bool,

        /// Print table metadata without writing PNGs.
        #[arg(long)]
        info_only: bool,
    },

    /// Run dcraw, then apply a Hald CLUT with GraphicsMagick/ImageMagick convert.
    Apply {
        /// RAW file to develop.
        raw: PathBuf,

        /// Output image path.
        #[arg(short, long)]
        output: PathBuf,

        /// Profile selector: Hald PNG path, RGBTable XMP path, or profile name.
        #[arg(short, long)]
        profile: String,

        /// Directory containing generated Hald PNGs, used when --profile is a name.
        #[arg(long, default_value = "hald")]
        hald_dir: PathBuf,

        /// Directory tree containing XMP profiles, used when --profile is a name.
        #[arg(long, default_value = ".")]
        profiles_root: PathBuf,

        /// Hald level to use when --profile points to an XMP or resolves to an XMP.
        #[arg(short = 'l', long, default_value_t = 8)]
        hald_level: u32,

        /// Extra arguments passed to dcraw before the RAW path.
        #[arg(long, value_delimiter = ' ', default_value = "-T -6 -W -w -o 1")]
        dcraw_args: Vec<String>,

        /// Camera input ICC profile for dcraw, or "embed". If omitted, dcraw uses its camera matrix.
        #[arg(long)]
        camera_profile: Option<String>,

        /// Path to dcraw binary.
        #[arg(long, default_value = "dcraw")]
        dcraw: PathBuf,

        /// Path to convert binary.
        #[arg(long, default_value = "convert")]
        convert: PathBuf,

        /// Keep the intermediate TIFF generated by dcraw.
        #[arg(long)]
        keep_intermediate: Option<PathBuf>,

        /// Disable Lightroom XMP grain emulation.
        #[arg(long)]
        no_grain: bool,

        /// Override grain as amount,size,frequency, each 0..100. Example: --grain 30,45,45
        #[arg(long)]
        grain: Option<String>,

        /// Built-in grain override: light, medium, or heavy.
        #[arg(long)]
        grain_preset: Option<String>,

        /// Seed for deterministic generated grain.
        #[arg(long, default_value_t = 1)]
        grain_seed: u64,

        /// JPEG quality when output path ends in .jpg or .jpeg.
        #[arg(long, default_value_t = 95)]
        jpg_quality: u8,
    },
}

fn main() -> Result<()> {
    match Cli::parse().command {
        CommandKind::Hald {
            input,
            output,
            hald_level,
            overwrite,
            info_only,
        } => run_hald(&input, &output, hald_level, overwrite, info_only),
        CommandKind::Apply {
            raw,
            output,
            profile,
            hald_dir,
            profiles_root,
            hald_level,
            dcraw_args,
            camera_profile,
            dcraw,
            convert,
            keep_intermediate,
            no_grain,
            grain,
            grain_preset,
            grain_seed,
            jpg_quality,
        } => run_apply(ApplyArgs {
            raw,
            output,
            profile,
            hald_dir,
            profiles_root,
            hald_level,
            dcraw_args,
            camera_profile,
            dcraw,
            convert,
            keep_intermediate,
            no_grain,
            grain,
            grain_preset,
            grain_seed,
            jpg_quality,
        }),
    }
}

fn run_hald(
    input: &Path,
    output: &Path,
    hald_level: u32,
    overwrite: bool,
    info_only: bool,
) -> Result<()> {
    let options = HaldOptions {
        hald_level,
        overwrite,
        info_only,
    };

    if input.is_dir() {
        let (converted, summary) = try_convert_dir(input, output, options)?;
        for profile in converted {
            eprintln!("{}", profile_info_line(&profile));
        }
        eprintln!(
            "converted {}, skipped {}",
            summary.converted, summary.skipped
        );
    } else {
        for profile in convert_path(input, output, options)? {
            eprintln!("{}", profile_info_line(&profile));
        }
    }

    Ok(())
}

struct ApplyArgs {
    raw: PathBuf,
    output: PathBuf,
    profile: String,
    hald_dir: PathBuf,
    profiles_root: PathBuf,
    hald_level: u32,
    dcraw_args: Vec<String>,
    camera_profile: Option<String>,
    dcraw: PathBuf,
    convert: PathBuf,
    keep_intermediate: Option<PathBuf>,
    no_grain: bool,
    grain: Option<String>,
    grain_preset: Option<String>,
    grain_seed: u64,
    jpg_quality: u8,
}

struct ResolvedProfile {
    hald_path: PathBuf,
    grain: GrainSettings,
}

fn run_apply(args: ApplyArgs) -> Result<()> {
    validate_output_format(&args.output)?;

    let temp_dir = Builder::new().prefix("mini-film-").tempdir()?;
    let mut resolved = resolve_profile(&args, temp_dir.path())?;
    if let Some(grain) =
        resolve_grain_override(args.grain.as_deref(), args.grain_preset.as_deref())?
    {
        resolved.grain = grain;
    }

    let intermediate = match &args.keep_intermediate {
        Some(path) => path.clone(),
        None => temp_dir.path().join("dcraw.tiff"),
    };
    let converted = temp_dir.path().join("converted.tiff");
    let final_source = if args.no_grain || !resolved.grain.is_enabled() {
        converted.clone()
    } else {
        temp_dir.path().join("grained.tiff")
    };

    run_dcraw(
        &args.dcraw,
        &args.dcraw_args,
        args.camera_profile.as_deref(),
        &args.raw,
        &intermediate,
    )?;
    run_convert(
        &args.convert,
        &intermediate,
        &resolved.hald_path,
        &converted,
    )?;

    if final_source != converted {
        apply_grain(&converted, &final_source, resolved.grain, args.grain_seed)?;
        eprintln!(
            "applied grain amount={} size={} frequency={}",
            resolved.grain.amount, resolved.grain.size, resolved.grain.frequency
        );
    }

    finalize_output(&args.convert, &final_source, &args.output, args.jpg_quality)?;

    eprintln!(
        "wrote {} using {}",
        args.output.display(),
        resolved.hald_path.display()
    );
    Ok(())
}

fn resolve_profile(args: &ApplyArgs, temp_dir: &Path) -> Result<ResolvedProfile> {
    let selector_path = Path::new(&args.profile);
    if selector_path.exists() {
        return profile_from_path(
            selector_path,
            args.hald_level,
            &args.profiles_root,
            temp_dir,
        );
    }

    if let Some(path) = find_xmp_by_name(&args.profiles_root, &args.profile)? {
        return profile_from_path(&path, args.hald_level, &args.profiles_root, temp_dir);
    }

    if let Some(path) = find_hald_by_name(&args.hald_dir, &args.profile)? {
        return Ok(ResolvedProfile {
            hald_path: path,
            grain: GrainSettings::default(),
        });
    }

    bail!(
        "could not resolve profile {:?} as a file, XMP name under {}, or Hald name under {}",
        args.profile,
        args.profiles_root.display(),
        args.hald_dir.display()
    );
}

fn profile_from_path(
    path: &Path,
    hald_level: u32,
    profiles_root: &Path,
    temp_dir: &Path,
) -> Result<ResolvedProfile> {
    match path.extension().and_then(|s| s.to_str()) {
        Some(ext) if ext.eq_ignore_ascii_case("png") => Ok(ResolvedProfile {
            hald_path: path.to_path_buf(),
            grain: GrainSettings::default(),
        }),
        Some(ext) if ext.eq_ignore_ascii_case("xmp") => {
            profile_from_xmp(path, hald_level, profiles_root, temp_dir)
        }
        Some(ext) => bail!("unsupported profile path extension .{ext}; expected .png or .xmp"),
        None => bail!("profile path has no extension: {}", path.display()),
    }
}

fn profile_from_xmp(
    path: &Path,
    hald_level: u32,
    profiles_root: &Path,
    temp_dir: &Path,
) -> Result<ResolvedProfile> {
    let recipe = extract_film_recipe(path)?;
    let source = if recipe.rgb_table.is_some() {
        path.to_path_buf()
    } else {
        resolve_recipe_profile(&recipe, profiles_root, path)
            .with_context(|| format!("resolving linked profile for preset {}", path.display()))?
    };

    let output = temp_dir.join("profile.hald.png");
    let converted = convert_xmp_to_hald(
        &source,
        &output,
        HaldOptions {
            hald_level,
            overwrite: true,
            info_only: false,
        },
    )?;
    eprintln!("{}", profile_info_line(&converted));
    Ok(ResolvedProfile {
        hald_path: output,
        grain: recipe.grain,
    })
}

fn resolve_recipe_profile(
    recipe: &mini_film::XmpFilmRecipe,
    profiles_root: &Path,
    preset_path: &Path,
) -> Result<PathBuf> {
    let mut roots = vec![profiles_root.to_path_buf()];
    if let Some(parent) = preset_path.parent() {
        roots.push(parent.to_path_buf());
        if let Some(grandparent) = parent.parent() {
            roots.push(grandparent.to_path_buf());
        }
    }

    for root in roots {
        if let Some(uuid) = &recipe.look_uuid {
            if let Some(path) = find_profile_by_uuid(&root, uuid)? {
                return Ok(path);
            }
        }
        if let Some(name) = &recipe.look_name {
            if let Some(path) = find_rgb_xmp_by_name(&root, name)? {
                return Ok(path);
            }
        }
    }

    bail!("preset does not contain a resolvable RGB table or linked Look UUID/name")
}

fn find_hald_by_name(root: &Path, name: &str) -> Result<Option<PathBuf>> {
    if !root.exists() {
        return Ok(None);
    }
    find_named_file(root, name, &["png"], true)
}

fn find_xmp_by_name(root: &Path, name: &str) -> Result<Option<PathBuf>> {
    if !root.exists() {
        return Ok(None);
    }
    find_named_file(root, name, &["xmp"], false)
}

fn find_rgb_xmp_by_name(root: &Path, name: &str) -> Result<Option<PathBuf>> {
    let Some(candidate) = find_xmp_by_name(root, name)? else {
        return Ok(None);
    };
    if extract_film_recipe(&candidate)
        .map(|recipe| recipe.rgb_table.is_some())
        .unwrap_or(false)
    {
        return Ok(Some(candidate));
    }

    let wanted = normalize_name(name);
    for entry in WalkDir::new(root).into_iter().filter_map(Result::ok) {
        if !entry.file_type().is_file() {
            continue;
        }
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("xmp") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        let candidate_name = normalize_name(stem)
            .trim_end_matches("profile")
            .trim()
            .to_string();
        if candidate_name != wanted {
            continue;
        }
        if extract_film_recipe(path)
            .map(|recipe| recipe.rgb_table.is_some())
            .unwrap_or(false)
        {
            return Ok(Some(path.to_path_buf()));
        }
    }

    Ok(None)
}

fn find_profile_by_uuid(root: &Path, uuid: &str) -> Result<Option<PathBuf>> {
    if !root.exists() {
        return Ok(None);
    }

    for entry in WalkDir::new(root).into_iter().filter_map(Result::ok) {
        if !entry.file_type().is_file() {
            continue;
        }
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("xmp") {
            continue;
        }
        let Ok(recipe) = extract_film_recipe(path) else {
            continue;
        };
        if recipe.rgb_table.is_none() {
            continue;
        }
        if recipe.uuid.as_deref() == Some(uuid) {
            return Ok(Some(path.to_path_buf()));
        }
    }

    Ok(None)
}

fn find_named_file(
    root: &Path,
    name: &str,
    extensions: &[&str],
    hald_png: bool,
) -> Result<Option<PathBuf>> {
    let wanted = normalize_name(name);
    let mut fuzzy_match = None;

    for entry in WalkDir::new(root).into_iter().filter_map(Result::ok) {
        if !entry.file_type().is_file() {
            continue;
        }

        let path = entry.path();
        let Some(ext) = path.extension().and_then(|s| s.to_str()) else {
            continue;
        };
        if !extensions
            .iter()
            .any(|candidate| ext.eq_ignore_ascii_case(candidate))
        {
            continue;
        }

        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        let mut candidate = normalize_name(stem);
        if hald_png {
            candidate = candidate.trim_end_matches("hald").trim().to_string();
        }
        candidate = candidate.trim_end_matches("profile").trim().to_string();

        if candidate == wanted {
            return Ok(Some(path.to_path_buf()));
        }
        if fuzzy_match.is_none() && candidate.contains(&wanted) {
            fuzzy_match = Some(path.to_path_buf());
        }
    }

    Ok(fuzzy_match)
}

fn normalize_name(value: &str) -> String {
    value
        .to_ascii_lowercase()
        .replace(['_', '-', '.'], " ")
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
}

fn resolve_grain_override(
    grain: Option<&str>,
    preset: Option<&str>,
) -> Result<Option<GrainSettings>> {
    match (grain, preset) {
        (Some(_), Some(_)) => bail!("use either --grain or --grain-preset, not both"),
        (Some(value), None) => Ok(Some(parse_grain(value)?)),
        (None, Some(value)) => Ok(Some(match normalize_name(value).as_str() {
            "none" | "off" => GrainSettings::default(),
            "light" => GrainSettings {
                amount: 18,
                size: 35,
                frequency: 40,
            },
            "medium" => GrainSettings {
                amount: 30,
                size: 45,
                frequency: 45,
            },
            "heavy" => GrainSettings {
                amount: 45,
                size: 60,
                frequency: 55,
            },
            _ => bail!("unknown grain preset {value:?}; use light, medium, heavy, or none"),
        })),
        (None, None) => Ok(None),
    }
}

fn parse_grain(value: &str) -> Result<GrainSettings> {
    let parts: Vec<_> = value.split(',').map(str::trim).collect();
    if parts.len() != 3 {
        bail!("--grain must be amount,size,frequency, for example --grain 30,45,45");
    }
    Ok(GrainSettings {
        amount: parse_grain_part(parts[0], "amount")?,
        size: parse_grain_part(parts[1], "size")?,
        frequency: parse_grain_part(parts[2], "frequency")?,
    })
}

fn parse_grain_part(value: &str, name: &str) -> Result<u8> {
    let parsed: u16 = value
        .parse()
        .with_context(|| format!("invalid grain {name} value {value:?}"))?;
    if parsed > 100 {
        bail!("grain {name} must be in 0..100");
    }
    Ok(parsed as u8)
}

fn run_dcraw(
    dcraw: &Path,
    dcraw_args: &[String],
    camera_profile: Option<&str>,
    raw: &Path,
    output_tiff: &Path,
) -> Result<()> {
    if let Some(parent) = output_tiff.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    }

    let output = File::create(output_tiff)
        .with_context(|| format!("creating intermediate {}", output_tiff.display()))?;

    let mut command = Command::new(dcraw);
    command.args(dcraw_args);
    if let Some(profile) = camera_profile {
        command.arg("-p").arg(profile);
    }
    let status = command
        .arg("-c")
        .arg(raw)
        .stdout(Stdio::from(output))
        .status()
        .with_context(|| format!("running {}", dcraw.display()))?;

    if !status.success() {
        bail!("dcraw failed with status {status}");
    }

    Ok(())
}

fn run_convert(convert: &Path, input_tiff: &Path, hald: &Path, output: &Path) -> Result<()> {
    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    }

    let status = Command::new(convert)
        .arg(input_tiff)
        .arg("-hald-clut")
        .arg(hald)
        .arg(output)
        .status()
        .with_context(|| format!("running {}", convert.display()))?;

    if !status.success() {
        bail!("convert failed with status {status}");
    }

    Ok(())
}

fn finalize_output(convert: &Path, input: &Path, output: &Path, jpg_quality: u8) -> Result<()> {
    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    }

    let ext = output_ext(output)?;
    let mut command = Command::new(convert);
    command.arg(input);

    if ext == "jpg" || ext == "jpeg" {
        command
            .arg("-depth")
            .arg("8")
            .arg("-quality")
            .arg(jpg_quality.clamp(1, 100).to_string());
    } else {
        command.arg("-depth").arg("10");
    }

    let status = command
        .arg(output)
        .status()
        .with_context(|| format!("running {}", convert.display()))?;

    if !status.success() {
        bail!("final export failed with status {status}");
    }

    Ok(())
}

fn validate_output_format(output: &Path) -> Result<()> {
    match output_ext(output)?.as_str() {
        "tif" | "tiff" | "jpg" | "jpeg" => Ok(()),
        ext => bail!("unsupported output extension .{ext}; use .tif/.tiff or .jpg/.jpeg"),
    }
}

fn output_ext(output: &Path) -> Result<String> {
    output
        .extension()
        .and_then(|s| s.to_str())
        .map(|s| s.to_ascii_lowercase())
        .ok_or_else(|| anyhow::anyhow!("output path must have .tif/.tiff or .jpg/.jpeg extension"))
}
