use std::{
    collections::hash_map::DefaultHasher,
    fs::{self, File},
    hash::{Hash, Hasher},
    path::{Path, PathBuf},
    process::{Command, Stdio},
    thread,
    time::{Duration, Instant, SystemTime, UNIX_EPOCH},
};

use anyhow::{Context, Result, bail};
use clap::{Parser, Subcommand, ValueEnum};
use indicatif::{MultiProgress, ProgressBar, ProgressStyle};
use mini_film::{
    GrainSettings, HaldOptions, SharpeningSettings, apply_grain, apply_grain_8bit, convert_path,
    convert_xmp_to_hald, extract_film_recipe, profile_info_line, try_convert_dir,
};
use rayon::ThreadPoolBuilder;
use tempfile::Builder;
use walkdir::WalkDir;

#[derive(Parser, Debug)]
#[command(
    version,
    about = "Develop RAW files with Lightroom-style film profile Hald CLUTs"
)]
struct Cli {
    #[command(subcommand)]
    command: CommandKind,
}

#[derive(Subcommand, Debug)]
enum CommandKind {
    /// Convert Adobe Camera Raw crs:RGBTable XMP profiles to Hald CLUT PNGs.
    Hald {
        /// XMP profile file or directory to convert.
        input: PathBuf,

        /// Output PNG path for a single file, or output directory for a directory input.
        #[arg(short, long, default_value = "hald")]
        output: PathBuf,

        /// Hald level. Level 8 produces a 64x64x64 CLUT stored as a 512x512 PNG.
        #[arg(short = 'l', long, default_value_t = 8)]
        hald_level: u32,

        /// Overwrite existing output files.
        #[arg(long)]
        overwrite: bool,

        /// Print table metadata without writing PNGs.
        #[arg(long)]
        info_only: bool,
    },

    /// Run dcraw, then apply a Hald CLUT with GraphicsMagick/ImageMagick convert.
    Apply {
        /// RAW file to develop.
        raw: PathBuf,

        /// Output image path.
        #[arg(short, long)]
        output: PathBuf,

        /// Profile selector: Hald PNG path, RGBTable XMP path, or profile name.
        #[arg(short, long)]
        profile: String,

        /// Directory containing generated Hald PNGs, used when --profile is a name.
        #[arg(long, default_value = "hald")]
        hald_dir: PathBuf,

        /// Directory tree containing XMP profiles, used when --profile is a name.
        #[arg(long, default_value = ".")]
        profiles_root: PathBuf,

        /// Hald level to use when --profile points to an XMP or resolves to an XMP.
        #[arg(short = 'l', long, default_value_t = 8)]
        hald_level: u32,

        /// Extra arguments passed to dcraw before the RAW path.
        #[arg(long, value_delimiter = ' ', default_value = "-T -6 -W -w -o 1")]
        dcraw_args: Vec<String>,

        /// RAW decoder: auto tries RawTherapee first and falls back to dcraw.
        #[arg(long, value_enum, default_value_t = RawEngine::Auto)]
        raw_engine: RawEngine,

        /// Path to rawtherapee-cli binary.
        #[arg(long, default_value = "rawtherapee-cli")]
        rawtherapee: PathBuf,

        /// Camera input ICC profile for dcraw, or "embed". If omitted, dcraw uses its camera matrix.
        #[arg(long)]
        camera_profile: Option<String>,

        /// Path to dcraw binary.
        #[arg(long, default_value = "dcraw")]
        dcraw: PathBuf,

        /// Path to convert binary.
        #[arg(long, default_value = "convert")]
        convert: PathBuf,

        /// Keep the intermediate TIFF generated by dcraw.
        #[arg(long)]
        keep_intermediate: Option<PathBuf>,

        /// Disable Lightroom XMP grain emulation.
        #[arg(long)]
        no_grain: bool,

        /// Override grain as amount,size,frequency, each 0..100. Example: --grain 30,45,45
        #[arg(long)]
        grain: Option<String>,

        /// Built-in grain override: light, medium, or heavy.
        #[arg(long)]
        grain_preset: Option<String>,

        /// Seed for deterministic generated grain. Defaults to current time of day.
        #[arg(long)]
        grain_seed: Option<u64>,

        /// JPEG quality when output path ends in .jpg or .jpeg.
        #[arg(long, default_value_t = 95)]
        jpg_quality: u8,
    },

    /// Apply a profile to every DNG/NEF file in an input folder and write JPEGs.
    Batch {
        /// Input folder scanned recursively for .dng/.DNG/.nef/.NEF files.
        input: PathBuf,

        /// Output folder. It is created if it does not exist.
        output: PathBuf,

        /// Profile selector: Hald PNG path, RGBTable XMP path, preset XMP path, or profile name.
        #[arg(short, long)]
        profile: String,

        /// Directory containing generated Hald PNGs, used when --profile is a name.
        #[arg(long, default_value = "hald")]
        hald_dir: PathBuf,

        /// Directory tree containing XMP profiles, used when --profile is a name.
        #[arg(long, default_value = ".")]
        profiles_root: PathBuf,

        /// Hald level to use when --profile points to an XMP or resolves to an XMP.
        #[arg(short = 'l', long, default_value_t = 8)]
        hald_level: u32,

        /// Extra arguments passed to dcraw before the RAW path.
        #[arg(long, value_delimiter = ' ', default_value = "-T -6 -W -w -o 1")]
        dcraw_args: Vec<String>,

        /// RAW decoder: auto tries RawTherapee first and falls back to dcraw.
        #[arg(long, value_enum, default_value_t = RawEngine::Auto)]
        raw_engine: RawEngine,

        /// Path to rawtherapee-cli binary.
        #[arg(long, default_value = "rawtherapee-cli")]
        rawtherapee: PathBuf,

        /// Camera input ICC profile for dcraw, or "embed". If omitted, dcraw uses its camera matrix.
        #[arg(long)]
        camera_profile: Option<String>,

        /// Path to dcraw binary.
        #[arg(long, default_value = "dcraw")]
        dcraw: PathBuf,

        /// Path to convert binary.
        #[arg(long, default_value = "convert")]
        convert: PathBuf,

        /// Disable Lightroom XMP grain emulation.
        #[arg(long)]
        no_grain: bool,

        /// Override grain as amount,size,frequency, each 0..100. Example: --grain 30,45,45
        #[arg(long)]
        grain: Option<String>,

        /// Built-in grain override: light, medium, or heavy.
        #[arg(long)]
        grain_preset: Option<String>,

        /// Base seed for deterministic generated grain. Defaults to current time of day.
        #[arg(long)]
        grain_seed: Option<u64>,

        /// JPEG quality for every output file.
        #[arg(long, default_value_t = 95)]
        jpg_quality: u8,
    },
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, ValueEnum)]
enum RawEngine {
    Auto,
    Rawtherapee,
    Dcraw,
}

fn main() -> Result<()> {
    configure_threads();

    match Cli::parse().command {
        CommandKind::Hald {
            input,
            output,
            hald_level,
            overwrite,
            info_only,
        } => run_hald(&input, &output, hald_level, overwrite, info_only),
        CommandKind::Apply {
            raw,
            output,
            profile,
            hald_dir,
            profiles_root,
            hald_level,
            dcraw_args,
            raw_engine,
            rawtherapee,
            camera_profile,
            dcraw,
            convert,
            keep_intermediate,
            no_grain,
            grain,
            grain_preset,
            grain_seed,
            jpg_quality,
        } => run_apply(ApplyArgs {
            raw,
            output,
            profile,
            hald_dir,
            profiles_root,
            hald_level,
            dcraw_args,
            raw_engine,
            rawtherapee,
            camera_profile,
            dcraw,
            convert,
            keep_intermediate,
            no_grain,
            grain,
            grain_preset,
            grain_seed,
            jpg_quality,
        }),
        CommandKind::Batch {
            input,
            output,
            profile,
            hald_dir,
            profiles_root,
            hald_level,
            dcraw_args,
            raw_engine,
            rawtherapee,
            camera_profile,
            dcraw,
            convert,
            no_grain,
            grain,
            grain_preset,
            grain_seed,
            jpg_quality,
        } => run_batch(BatchArgs {
            input,
            output,
            profile,
            hald_dir,
            profiles_root,
            hald_level,
            dcraw_args,
            raw_engine,
            rawtherapee,
            camera_profile,
            dcraw,
            convert,
            no_grain,
            grain,
            grain_preset,
            grain_seed,
            jpg_quality,
        }),
    }
}

fn run_hald(
    input: &Path,
    output: &Path,
    hald_level: u32,
    overwrite: bool,
    info_only: bool,
) -> Result<()> {
    let options = HaldOptions {
        hald_level,
        overwrite,
        info_only,
    };

    if input.is_dir() {
        let (converted, summary) = try_convert_dir(input, output, options)?;
        for profile in converted {
            eprintln!("{}", profile_info_line(&profile));
        }
        eprintln!(
            "converted {}, skipped {}",
            summary.converted, summary.skipped
        );
    } else {
        for profile in convert_path(input, output, options)? {
            eprintln!("{}", profile_info_line(&profile));
        }
    }

    Ok(())
}

struct ApplyArgs {
    raw: PathBuf,
    output: PathBuf,
    profile: String,
    hald_dir: PathBuf,
    profiles_root: PathBuf,
    hald_level: u32,
    dcraw_args: Vec<String>,
    raw_engine: RawEngine,
    rawtherapee: PathBuf,
    camera_profile: Option<String>,
    dcraw: PathBuf,
    convert: PathBuf,
    keep_intermediate: Option<PathBuf>,
    no_grain: bool,
    grain: Option<String>,
    grain_preset: Option<String>,
    grain_seed: Option<u64>,
    jpg_quality: u8,
}

struct BatchArgs {
    input: PathBuf,
    output: PathBuf,
    profile: String,
    hald_dir: PathBuf,
    profiles_root: PathBuf,
    hald_level: u32,
    dcraw_args: Vec<String>,
    raw_engine: RawEngine,
    rawtherapee: PathBuf,
    camera_profile: Option<String>,
    dcraw: PathBuf,
    convert: PathBuf,
    no_grain: bool,
    grain: Option<String>,
    grain_preset: Option<String>,
    grain_seed: Option<u64>,
    jpg_quality: u8,
}

struct ResolvedProfile {
    hald_path: PathBuf,
    grain: GrainSettings,
    sharpening: SharpeningSettings,
}

struct ApplyJob<'a> {
    raw: &'a Path,
    output: &'a Path,
    dcraw_args: &'a [String],
    raw_engine: RawEngine,
    rawtherapee: &'a Path,
    camera_profile: Option<&'a str>,
    dcraw: &'a Path,
    convert: &'a Path,
    keep_intermediate: Option<&'a Path>,
    no_grain: bool,
    jpg_quality: u8,
    quiet: bool,
}

struct ApplyProgress<'a> {
    file: &'a ProgressBar,
    started: Instant,
}

fn run_apply(args: ApplyArgs) -> Result<()> {
    validate_output_format(&args.output)?;

    let temp_dir = Builder::new().prefix("mini-film-").tempdir()?;
    let mut resolved = resolve_profile(&args, temp_dir.path())?;
    if let Some(grain) =
        resolve_grain_override(args.grain.as_deref(), args.grain_preset.as_deref())?
    {
        resolved.grain = grain;
    }
    let grain_seed = args.grain_seed.unwrap_or_else(time_of_day_seed);

    apply_resolved(
        ApplyJob {
            raw: &args.raw,
            output: &args.output,
            dcraw_args: &args.dcraw_args,
            raw_engine: args.raw_engine,
            rawtherapee: &args.rawtherapee,
            camera_profile: args.camera_profile.as_deref(),
            dcraw: &args.dcraw,
            convert: &args.convert,
            keep_intermediate: args.keep_intermediate.as_deref(),
            no_grain: args.no_grain,
            jpg_quality: args.jpg_quality,
            quiet: false,
        },
        &resolved,
        grain_seed,
        temp_dir.path(),
        None,
    )?;

    eprintln!(
        "wrote {} using {}",
        args.output.display(),
        resolved.hald_path.display()
    );
    Ok(())
}

fn apply_resolved(
    job: ApplyJob<'_>,
    resolved: &ResolvedProfile,
    grain_seed: u64,
    temp_dir: &Path,
    progress: Option<&ApplyProgress<'_>>,
) -> Result<()> {
    validate_output_format(job.output)?;

    let grain_enabled = !job.no_grain && resolved.grain.is_enabled();

    if !grain_enabled && job.keep_intermediate.is_none() && job.raw_engine == RawEngine::Dcraw {
        let step = if resolved.sharpening.is_enabled() {
            "dcraw + hald/sharpen + export"
        } else {
            "dcraw + hald + export"
        };
        progress_step(progress, 1, step);
        run_dcraw_convert_final(
            job.dcraw,
            job.dcraw_args,
            job.camera_profile,
            job.raw,
            job.convert,
            &resolved.hald_path,
            resolved.sharpening,
            job.output,
            job.jpg_quality,
        )?;
        progress_step(progress, 5, "done");
        return Ok(());
    }

    let intermediate = job
        .keep_intermediate
        .map(Path::to_path_buf)
        .unwrap_or_else(|| temp_dir.join("dcraw.tif"));
    let cleanup_intermediate = job.keep_intermediate.is_none();
    let output_ext = output_ext(job.output)?;
    let jpeg_output = output_ext == "jpg" || output_ext == "jpeg";
    let converted = if grain_enabled && jpeg_output {
        temp_dir.join("converted-8.ppm")
    } else {
        temp_dir.join("converted.tif")
    };
    let final_source = if grain_enabled && !jpeg_output {
        temp_dir.join("grained.tif")
    } else {
        converted.clone()
    };

    progress_step(progress, 1, raw_engine_step(job.raw_engine));
    run_raw_develop(
        job.raw_engine,
        job.rawtherapee,
        job.dcraw,
        job.dcraw_args,
        job.camera_profile,
        job.raw,
        &intermediate,
        job.quiet,
    )?;
    progress_step(
        progress,
        2,
        if resolved.sharpening.is_enabled() {
            "hald/sharpen"
        } else {
            "hald"
        },
    );
    run_convert_depth(
        job.convert,
        &intermediate,
        &resolved.hald_path,
        resolved.sharpening,
        &converted,
        (grain_enabled && jpeg_output).then_some(8),
    )?;
    if cleanup_intermediate {
        remove_temp_file(&intermediate)?;
    }

    if grain_enabled && jpeg_output {
        progress_step(progress, 3, "grain");
        let grained = temp_dir.join("grained-8.ppm");
        apply_grain_8bit(&converted, &grained, resolved.grain, grain_seed)?;
        remove_temp_file(&converted)?;
        if progress.is_none() {
            eprintln!(
                "applied grain amount={} size={} frequency={}",
                resolved.grain.amount, resolved.grain.size, resolved.grain.frequency
            );
        }
        progress_step(progress, 4, "jpeg export");
        finalize_output(job.convert, &grained, job.output, job.jpg_quality)?;
        remove_temp_file(&grained)?;
    } else if final_source != converted {
        progress_step(progress, 3, "grain");
        apply_grain(&converted, &final_source, resolved.grain, grain_seed)?;
        remove_temp_file(&converted)?;
        if progress.is_none() {
            eprintln!(
                "applied grain amount={} size={} frequency={}",
                resolved.grain.amount, resolved.grain.size, resolved.grain.frequency
            );
        }
    }

    if !jpeg_output || !grain_enabled {
        progress_step(progress, 4, "export");
        finalize_output(job.convert, &final_source, job.output, job.jpg_quality)?;
        if final_source != converted {
            remove_temp_file(&final_source)?;
        }
    }

    progress_step(progress, 5, "done");
    Ok(())
}

fn run_batch(args: BatchArgs) -> Result<()> {
    if !args.input.is_dir() {
        bail!("batch input is not a directory: {}", args.input.display());
    }
    fs::create_dir_all(&args.output)
        .with_context(|| format!("creating {}", args.output.display()))?;

    let raws = collect_batch_inputs(&args.input)?;
    if raws.is_empty() {
        bail!("no DNG/NEF files found under {}", args.input.display());
    }

    let temp_dir = Builder::new().prefix("mini-film-batch-").tempdir()?;
    let apply_args = ApplyArgs {
        raw: PathBuf::new(),
        output: PathBuf::new(),
        profile: args.profile.clone(),
        hald_dir: args.hald_dir.clone(),
        profiles_root: args.profiles_root.clone(),
        hald_level: args.hald_level,
        dcraw_args: args.dcraw_args.clone(),
        raw_engine: args.raw_engine,
        rawtherapee: args.rawtherapee.clone(),
        camera_profile: args.camera_profile.clone(),
        dcraw: args.dcraw.clone(),
        convert: args.convert.clone(),
        keep_intermediate: None,
        no_grain: args.no_grain,
        grain: args.grain.clone(),
        grain_preset: args.grain_preset.clone(),
        grain_seed: args.grain_seed,
        jpg_quality: args.jpg_quality,
    };
    let mut resolved = resolve_profile(&apply_args, temp_dir.path())?;
    if let Some(grain) =
        resolve_grain_override(args.grain.as_deref(), args.grain_preset.as_deref())?
    {
        resolved.grain = grain;
    }
    let base_seed = args.grain_seed.unwrap_or_else(time_of_day_seed);

    let multi = MultiProgress::new();
    let batch = multi.add(ProgressBar::new(raws.len() as u64));
    batch.set_style(batch_progress_style());
    batch.set_message("starting");
    let file = multi.add(ProgressBar::new(5));
    file.set_style(file_progress_style());
    file.set_message("waiting");

    let batch_start = Instant::now();
    let mut failures = Vec::new();
    for (index, raw) in raws.iter().enumerate() {
        let output = batch_output_path(&args.input, &args.output, raw)?;
        if let Some(parent) = output.parent() {
            fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
        }

        let display_name = raw
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or("<unknown>")
            .to_string();
        batch.set_position((index + 1) as u64);
        batch.set_message(display_name.clone());
        file.set_position(0);
        file.set_message(format!("{display_name}: queued"));

        let file_start = Instant::now();
        let progress = ApplyProgress {
            file: &file,
            started: file_start,
        };
        let file_temp = temp_dir.path().join(format!("file-{index}"));
        fs::create_dir_all(&file_temp)
            .with_context(|| format!("creating {}", file_temp.display()))?;
        let seed = per_file_seed(base_seed, index as u64, raw);
        let result = apply_resolved(
            ApplyJob {
                raw,
                output: &output,
                dcraw_args: &args.dcraw_args,
                raw_engine: args.raw_engine,
                rawtherapee: &args.rawtherapee,
                camera_profile: args.camera_profile.as_deref(),
                dcraw: &args.dcraw,
                convert: &args.convert,
                keep_intermediate: None,
                no_grain: args.no_grain,
                jpg_quality: args.jpg_quality,
                quiet: true,
            },
            &resolved,
            seed,
            &file_temp,
            Some(&progress),
        );

        match result {
            Ok(()) => {
                file.set_message(format!(
                    "{}: done in {}",
                    display_name,
                    format_duration(file_start.elapsed())
                ));
            }
            Err(err) => {
                file.set_message(format!(
                    "{}: failed after {}",
                    display_name,
                    format_duration(file_start.elapsed())
                ));
                failures.push((raw.clone(), err));
            }
        }
    }

    if failures.is_empty() {
        batch.finish_with_message(format!(
            "done {} files in {}",
            raws.len(),
            format_duration(batch_start.elapsed())
        ));
        file.finish_and_clear();
        Ok(())
    } else {
        batch.abandon_with_message(format!(
            "failed {}/{} files in {}",
            failures.len(),
            raws.len(),
            format_duration(batch_start.elapsed())
        ));
        for (path, err) in failures {
            batch.println(format!("failed {}: {err:#}", path.display()));
        }
        bail!("batch finished with failures")
    }
}

fn collect_batch_inputs(input: &Path) -> Result<Vec<PathBuf>> {
    let mut raws = Vec::new();
    for entry in WalkDir::new(input).into_iter().filter_map(Result::ok) {
        if !entry.file_type().is_file() {
            continue;
        }
        if is_batch_raw(entry.path()) {
            raws.push(entry.path().to_path_buf());
        }
    }
    raws.sort();
    Ok(raws)
}

fn is_batch_raw(path: &Path) -> bool {
    matches!(
        path.extension().and_then(|s| s.to_str()),
        Some(ext)
            if ext.eq_ignore_ascii_case("dng") || ext.eq_ignore_ascii_case("nef")
    )
}

fn batch_output_path(input_root: &Path, output_root: &Path, raw: &Path) -> Result<PathBuf> {
    let rel = raw
        .strip_prefix(input_root)
        .with_context(|| format!("mapping {} under {}", raw.display(), input_root.display()))?;
    let parent = rel.parent().unwrap_or_else(|| Path::new(""));
    let stem = rel
        .file_stem()
        .and_then(|s| s.to_str())
        .ok_or_else(|| anyhow::anyhow!("input has no valid stem: {}", raw.display()))?;
    Ok(output_root.join(parent).join(format!("{stem}.jpg")))
}

fn batch_progress_style() -> ProgressStyle {
    ProgressStyle::with_template(
        "{spinner:.green} batch [{elapsed_precise}] [{wide_bar:.cyan/blue}] {pos}/{len} {msg}",
    )
    .unwrap()
    .progress_chars("#>-")
}

fn file_progress_style() -> ProgressStyle {
    ProgressStyle::with_template(
        "{spinner:.green} file  [{elapsed_precise}] [{wide_bar:.magenta/blue}] {pos}/{len} {msg}",
    )
    .unwrap()
    .progress_chars("#>-")
}

fn progress_step(progress: Option<&ApplyProgress<'_>>, position: u64, step: &str) {
    let Some(progress) = progress else {
        return;
    };
    progress.file.set_position(position);
    progress.file.set_message(format!(
        "{} ({})",
        step,
        format_duration(progress.started.elapsed())
    ));
}

fn per_file_seed(base_seed: u64, index: u64, path: &Path) -> u64 {
    let mut hasher = DefaultHasher::new();
    path.hash(&mut hasher);
    base_seed ^ index.wrapping_mul(0x9E37_79B9_7F4A_7C15) ^ hasher.finish()
}

fn format_duration(duration: Duration) -> String {
    let seconds = duration.as_secs();
    let millis = duration.subsec_millis();
    if seconds >= 60 {
        format!("{}m{:02}.{:03}s", seconds / 60, seconds % 60, millis)
    } else {
        format!("{seconds}.{millis:03}s")
    }
}

fn remove_temp_file(path: &Path) -> Result<()> {
    match fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(err) => Err(err).with_context(|| format!("removing temporary {}", path.display())),
    }
}

fn configure_threads() {
    let threads = thread::available_parallelism()
        .map(|threads| threads.get())
        .unwrap_or(1);
    let _ = ThreadPoolBuilder::new().num_threads(threads).build_global();
}

fn time_of_day_seed() -> u64 {
    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default();
    let seconds_in_day = now.as_secs() % 86_400;
    (seconds_in_day << 32) ^ now.subsec_nanos() as u64
}

fn resolve_profile(args: &ApplyArgs, temp_dir: &Path) -> Result<ResolvedProfile> {
    let selector_path = Path::new(&args.profile);
    if selector_path.exists() {
        return profile_from_path(
            selector_path,
            args.hald_level,
            &args.profiles_root,
            temp_dir,
        );
    }

    if let Some(path) = find_xmp_by_name(&args.profiles_root, &args.profile)? {
        return profile_from_path(&path, args.hald_level, &args.profiles_root, temp_dir);
    }

    if let Some(path) = find_hald_by_name(&args.hald_dir, &args.profile)? {
        return Ok(ResolvedProfile {
            hald_path: path,
            grain: GrainSettings::default(),
            sharpening: SharpeningSettings::default(),
        });
    }

    bail!(
        "could not resolve profile {:?} as a file, XMP name under {}, or Hald name under {}",
        args.profile,
        args.profiles_root.display(),
        args.hald_dir.display()
    );
}

fn profile_from_path(
    path: &Path,
    hald_level: u32,
    profiles_root: &Path,
    temp_dir: &Path,
) -> Result<ResolvedProfile> {
    match path.extension().and_then(|s| s.to_str()) {
        Some(ext) if ext.eq_ignore_ascii_case("png") => Ok(ResolvedProfile {
            hald_path: path.to_path_buf(),
            grain: GrainSettings::default(),
            sharpening: SharpeningSettings::default(),
        }),
        Some(ext) if ext.eq_ignore_ascii_case("xmp") => {
            profile_from_xmp(path, hald_level, profiles_root, temp_dir)
        }
        Some(ext) => bail!("unsupported profile path extension .{ext}; expected .png or .xmp"),
        None => bail!("profile path has no extension: {}", path.display()),
    }
}

fn profile_from_xmp(
    path: &Path,
    hald_level: u32,
    profiles_root: &Path,
    temp_dir: &Path,
) -> Result<ResolvedProfile> {
    let recipe = extract_film_recipe(path)?;
    let source = if recipe.rgb_table.is_some() {
        path.to_path_buf()
    } else {
        resolve_recipe_profile(&recipe, profiles_root, path)
            .with_context(|| format!("resolving linked profile for preset {}", path.display()))?
    };

    let output = temp_dir.join("profile.hald.png");
    let converted = convert_xmp_to_hald(
        &source,
        &output,
        HaldOptions {
            hald_level,
            overwrite: true,
            info_only: false,
        },
    )?;
    eprintln!("{}", profile_info_line(&converted));
    Ok(ResolvedProfile {
        hald_path: output,
        grain: recipe.grain,
        sharpening: converted.sharpening,
    })
}

fn resolve_recipe_profile(
    recipe: &mini_film::XmpFilmRecipe,
    profiles_root: &Path,
    preset_path: &Path,
) -> Result<PathBuf> {
    let mut roots = vec![profiles_root.to_path_buf()];
    if let Some(parent) = preset_path.parent() {
        roots.push(parent.to_path_buf());
        if let Some(grandparent) = parent.parent() {
            roots.push(grandparent.to_path_buf());
        }
    }

    for root in roots {
        if let Some(uuid) = &recipe.look_uuid {
            if let Some(path) = find_profile_by_uuid(&root, uuid)? {
                return Ok(path);
            }
        }
        if let Some(name) = &recipe.look_name {
            if let Some(path) = find_rgb_xmp_by_name(&root, name)? {
                return Ok(path);
            }
        }
    }

    bail!("preset does not contain a resolvable RGB table or linked Look UUID/name")
}

fn find_hald_by_name(root: &Path, name: &str) -> Result<Option<PathBuf>> {
    if !root.exists() {
        return Ok(None);
    }
    find_named_file(root, name, &["png"], true)
}

fn find_xmp_by_name(root: &Path, name: &str) -> Result<Option<PathBuf>> {
    if !root.exists() {
        return Ok(None);
    }
    find_named_file(root, name, &["xmp"], false)
}

fn find_rgb_xmp_by_name(root: &Path, name: &str) -> Result<Option<PathBuf>> {
    let Some(candidate) = find_xmp_by_name(root, name)? else {
        return Ok(None);
    };
    if extract_film_recipe(&candidate)
        .map(|recipe| recipe.rgb_table.is_some())
        .unwrap_or(false)
    {
        return Ok(Some(candidate));
    }

    let wanted = normalize_name(name);
    for entry in WalkDir::new(root).into_iter().filter_map(Result::ok) {
        if !entry.file_type().is_file() {
            continue;
        }
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("xmp") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        let candidate_name = normalize_name(stem)
            .trim_end_matches("profile")
            .trim()
            .to_string();
        if candidate_name != wanted {
            continue;
        }
        if extract_film_recipe(path)
            .map(|recipe| recipe.rgb_table.is_some())
            .unwrap_or(false)
        {
            return Ok(Some(path.to_path_buf()));
        }
    }

    Ok(None)
}

fn find_profile_by_uuid(root: &Path, uuid: &str) -> Result<Option<PathBuf>> {
    if !root.exists() {
        return Ok(None);
    }

    for entry in WalkDir::new(root).into_iter().filter_map(Result::ok) {
        if !entry.file_type().is_file() {
            continue;
        }
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("xmp") {
            continue;
        }
        let Ok(recipe) = extract_film_recipe(path) else {
            continue;
        };
        if recipe.rgb_table.is_none() {
            continue;
        }
        if recipe.uuid.as_deref() == Some(uuid) {
            return Ok(Some(path.to_path_buf()));
        }
    }

    Ok(None)
}

fn find_named_file(
    root: &Path,
    name: &str,
    extensions: &[&str],
    hald_png: bool,
) -> Result<Option<PathBuf>> {
    let wanted = normalize_name(name);
    let mut fuzzy_match = None;

    for entry in WalkDir::new(root).into_iter().filter_map(Result::ok) {
        if !entry.file_type().is_file() {
            continue;
        }

        let path = entry.path();
        let Some(ext) = path.extension().and_then(|s| s.to_str()) else {
            continue;
        };
        if !extensions
            .iter()
            .any(|candidate| ext.eq_ignore_ascii_case(candidate))
        {
            continue;
        }

        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        let mut candidate = normalize_name(stem);
        if hald_png {
            candidate = candidate.trim_end_matches("hald").trim().to_string();
        }
        candidate = candidate.trim_end_matches("profile").trim().to_string();

        if candidate == wanted {
            return Ok(Some(path.to_path_buf()));
        }
        if fuzzy_match.is_none() && candidate.contains(&wanted) {
            fuzzy_match = Some(path.to_path_buf());
        }
    }

    Ok(fuzzy_match)
}

fn normalize_name(value: &str) -> String {
    value
        .to_ascii_lowercase()
        .replace(['_', '-', '.'], " ")
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
}

fn resolve_grain_override(
    grain: Option<&str>,
    preset: Option<&str>,
) -> Result<Option<GrainSettings>> {
    match (grain, preset) {
        (Some(_), Some(_)) => bail!("use either --grain or --grain-preset, not both"),
        (Some(value), None) => Ok(Some(parse_grain(value)?)),
        (None, Some(value)) => Ok(Some(match normalize_name(value).as_str() {
            "none" | "off" => GrainSettings::default(),
            "light" => GrainSettings {
                amount: 18,
                size: 35,
                frequency: 40,
            },
            "medium" => GrainSettings {
                amount: 30,
                size: 45,
                frequency: 45,
            },
            "heavy" => GrainSettings {
                amount: 45,
                size: 60,
                frequency: 55,
            },
            _ => bail!("unknown grain preset {value:?}; use light, medium, heavy, or none"),
        })),
        (None, None) => Ok(None),
    }
}

fn parse_grain(value: &str) -> Result<GrainSettings> {
    let parts: Vec<_> = value.split(',').map(str::trim).collect();
    if parts.len() != 3 {
        bail!("--grain must be amount,size,frequency, for example --grain 30,45,45");
    }
    Ok(GrainSettings {
        amount: parse_grain_part(parts[0], "amount")?,
        size: parse_grain_part(parts[1], "size")?,
        frequency: parse_grain_part(parts[2], "frequency")?,
    })
}

fn parse_grain_part(value: &str, name: &str) -> Result<u8> {
    let parsed: u16 = value
        .parse()
        .with_context(|| format!("invalid grain {name} value {value:?}"))?;
    if parsed > 100 {
        bail!("grain {name} must be in 0..100");
    }
    Ok(parsed as u8)
}

fn raw_engine_step(engine: RawEngine) -> &'static str {
    match engine {
        RawEngine::Auto => "rawtherapee",
        RawEngine::Rawtherapee => "rawtherapee",
        RawEngine::Dcraw => "dcraw",
    }
}

fn run_raw_develop(
    engine: RawEngine,
    rawtherapee: &Path,
    dcraw: &Path,
    dcraw_args: &[String],
    camera_profile: Option<&str>,
    raw: &Path,
    output_tiff: &Path,
    quiet: bool,
) -> Result<()> {
    match engine {
        RawEngine::Rawtherapee => run_rawtherapee(rawtherapee, raw, output_tiff, quiet),
        RawEngine::Dcraw => run_dcraw(dcraw, dcraw_args, camera_profile, raw, output_tiff, quiet),
        RawEngine::Auto => match run_rawtherapee(rawtherapee, raw, output_tiff, quiet) {
            Ok(()) => Ok(()),
            Err(rt_err) => {
                if !quiet {
                    eprintln!(
                        "rawtherapee failed for {}, falling back to dcraw: {rt_err:#}",
                        raw.display()
                    );
                }
                run_dcraw(dcraw, dcraw_args, camera_profile, raw, output_tiff, quiet)
            }
        },
    }
}

fn run_rawtherapee(rawtherapee: &Path, raw: &Path, output_tiff: &Path, quiet: bool) -> Result<()> {
    if let Some(parent) = output_tiff.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    }

    let mut command = Command::new(rawtherapee);
    command
        .arg("-q")
        .arg("-Y")
        .arg("-o")
        .arg(output_tiff)
        .arg("-t")
        .arg("-b16")
        .arg("-c")
        .arg(raw);
    if quiet {
        command.stdout(Stdio::null()).stderr(Stdio::null());
    }
    let status = command
        .status()
        .with_context(|| format!("running {}", rawtherapee.display()))?;

    if !status.success() {
        bail!("rawtherapee failed with status {status}");
    }
    if !output_tiff.exists() {
        bail!(
            "rawtherapee finished without creating {}",
            output_tiff.display()
        );
    }

    Ok(())
}

fn run_dcraw(
    dcraw: &Path,
    dcraw_args: &[String],
    camera_profile: Option<&str>,
    raw: &Path,
    output_tiff: &Path,
    quiet: bool,
) -> Result<()> {
    if let Some(parent) = output_tiff.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    }

    let output = File::create(output_tiff)
        .with_context(|| format!("creating intermediate {}", output_tiff.display()))?;

    let mut command = Command::new(dcraw);
    command.args(dcraw_args);
    if let Some(profile) = camera_profile {
        command.arg("-p").arg(profile);
    }
    if quiet {
        command.stderr(Stdio::null());
    }
    let status = command
        .arg("-c")
        .arg(raw)
        .stdout(Stdio::from(output))
        .status()
        .with_context(|| format!("running {}", dcraw.display()))?;

    if !status.success() {
        bail!("dcraw failed with status {status}");
    }

    Ok(())
}

fn run_dcraw_convert_final(
    dcraw: &Path,
    dcraw_args: &[String],
    camera_profile: Option<&str>,
    raw: &Path,
    convert: &Path,
    hald: &Path,
    sharpening: SharpeningSettings,
    output: &Path,
    jpg_quality: u8,
) -> Result<()> {
    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    }

    let mut dcraw_command = Command::new(dcraw);
    dcraw_command.args(dcraw_args);
    if let Some(profile) = camera_profile {
        dcraw_command.arg("-p").arg(profile);
    }
    let mut dcraw_child = dcraw_command
        .arg("-c")
        .arg(raw)
        .stdout(Stdio::piped())
        .spawn()
        .with_context(|| format!("running {}", dcraw.display()))?;

    let dcraw_stdout = dcraw_child
        .stdout
        .take()
        .ok_or_else(|| anyhow::anyhow!("failed to capture dcraw stdout"))?;

    let mut convert_command = Command::new(convert);
    convert_command.arg("tiff:-").arg("-hald-clut").arg(hald);
    add_sharpening_args(&mut convert_command, sharpening);
    add_final_convert_args(&mut convert_command, output, jpg_quality)?;
    let mut convert_child = convert_command
        .stdin(Stdio::from(dcraw_stdout))
        .spawn()
        .with_context(|| format!("running {}", convert.display()))?;

    let convert_status = convert_child.wait()?;
    let dcraw_status = dcraw_child.wait()?;

    if !dcraw_status.success() {
        bail!("dcraw failed with status {dcraw_status}");
    }
    if !convert_status.success() {
        bail!("convert failed with status {convert_status}");
    }

    Ok(())
}

fn run_convert_depth(
    convert: &Path,
    input_tiff: &Path,
    hald: &Path,
    sharpening: SharpeningSettings,
    output: &Path,
    depth: Option<u8>,
) -> Result<()> {
    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    }

    let mut command = Command::new(convert);
    command.arg(input_tiff).arg("-hald-clut").arg(hald);
    add_sharpening_args(&mut command, sharpening);
    if let Some(depth) = depth {
        command.arg("-depth").arg(depth.to_string());
    }

    let status = command
        .arg(output)
        .status()
        .with_context(|| format!("running {}", convert.display()))?;

    if !status.success() {
        bail!("convert failed with status {status}");
    }

    Ok(())
}

fn add_sharpening_args(command: &mut Command, sharpening: SharpeningSettings) {
    if !sharpening.is_enabled() {
        return;
    }

    let radius = sharpening.radius.clamp(0.1, 3.0);
    let sigma = (radius * (0.65 + sharpening.detail.clamp(0.0, 100.0) / 250.0)).clamp(0.1, 3.5);
    let amount = (sharpening.amount.clamp(0.0, 150.0) / 100.0).clamp(0.0, 1.5);
    let threshold = (sharpening.masking.clamp(0.0, 100.0) / 1000.0).clamp(0.0, 0.1);
    command
        .arg("-unsharp")
        .arg(format!("{radius:.2}x{sigma:.2}+{amount:.2}+{threshold:.3}"));
}

fn finalize_output(convert: &Path, input: &Path, output: &Path, jpg_quality: u8) -> Result<()> {
    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    }

    let mut command = Command::new(convert);
    command.arg(input);
    add_final_convert_args(&mut command, output, jpg_quality)?;

    let status = command
        .status()
        .with_context(|| format!("running {}", convert.display()))?;

    if !status.success() {
        bail!("final export failed with status {status}");
    }

    Ok(())
}

fn add_final_convert_args(command: &mut Command, output: &Path, jpg_quality: u8) -> Result<()> {
    let ext = output_ext(output)?;

    if ext == "jpg" || ext == "jpeg" {
        command
            .arg("-depth")
            .arg("8")
            .arg("-quality")
            .arg(jpg_quality.clamp(1, 100).to_string());
    }

    command.arg(output);
    Ok(())
}

fn validate_output_format(output: &Path) -> Result<()> {
    match output_ext(output)?.as_str() {
        "tif" | "tiff" | "jpg" | "jpeg" => Ok(()),
        ext => bail!("unsupported output extension .{ext}; use .tif/.tiff or .jpg/.jpeg"),
    }
}

fn output_ext(output: &Path) -> Result<String> {
    output
        .extension()
        .and_then(|s| s.to_str())
        .map(|s| s.to_ascii_lowercase())
        .ok_or_else(|| anyhow::anyhow!("output path must have .tif/.tiff or .jpg/.jpeg extension"))
}
